version: "3.7"

services:
  app:
   build: .
   depends_on:
    - db
   environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=sql1234

  db:
   image: postgres:latest
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=sql1234
    - POSTGRES_DB=postgres
   ports:
    - "5432:5432"