replicaCount: 1

image:
  repository: customer-model
  tag: latest
  pullPolicy: IfNotPresent

postgres:
  username: postgres
  password: password
  db: postgres
  port: 5432

service:
  type: ClusterIP
  port: 8089

prometheus:
  enabled: true
  port: 9090

resources: {}

